@startuml
skinparam shadowing false
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}

title Vertical Pod Autoscaler (VPA) 工作流程图

actor User as user

rectangle "Vertical Pod\nAutoScaler" as vpa
rectangle "VPA Updater" as updater
rectangle "VPA Admission\nPlugin" as admission
rectangle "VPA Recommender" as recommender
rectangle "Prometheus" as prometheus

rectangle "Deployment" as deploy #orange
rectangle "Pod" as pod #FFCCBB {
  rectangle "resources:\nrequests:\ncpu: 2\nmemory: 20G" as podres #FF6600
}

rectangle "target:\ncpu: 2\nmemory: 20G" as target #FF6600

' User 配置 VPA
user --> vpa : 配置 VPA

' VPA <-> Recommender
vpa --> recommender : 读取配置
recommender --> prometheus : 读取 Pod 资源使用情况
prometheus --> recommender : 收集 Pod 指标
recommender --> vpa : 给出资源请求建议

' VPA Updater
vpa --> updater : 监控 Pod 资源伸缩建议
updater --> pod : 删除 Pod

' Admission Plugin 修改 Pod spec
admission --> vpa : 获取资源请求建议
admission --> pod : Pod 变形，设置建议资源

' VPA → Admission
vpa --> admission : 给出资源请求建议

' Deployment 重建 Pod
deploy --> pod : 重建 Pod

' 建议资源展示
pod --> target : 建议值

@enduml
