FROM debian
LABEL maintainer="pachirode"
RUN http_proxy=http://192.168.1.4:7890 https_proxy=http://192.168.1.4:7890 \
    apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*
COPY index.html /usr/share/nginx/html/
EXPOSE 80
ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]