//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&XXX{}, func(obj interface{}) { SetObjectDefaults_XXX(obj.(*XXX)) })
	scheme.AddTypeDefaultingFunc(&XXXList{}, func(obj interface{}) { SetObjectDefaults_XXXList(obj.(*XXXList)) })
	return nil
}

func SetObjectDefaults_XXX(in *XXX) {
	SetDefaults_XXX(in)
	SetDefaults_XXXSpec(&in.Spec)
}

func SetObjectDefaults_XXXList(in *XXXList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_XXX(a)
	}
}
