//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*XXX)(nil), (*XXX)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXX_To_v1beta1_XXX(a.(*XXX), b.(*XXX), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXX)(nil), (*XXX)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXX_To_v1beta1_XXX(a.(*XXX), b.(*XXX), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXList)(nil), (*XXXList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXList_To_v1beta1_XXXList(a.(*XXXList), b.(*XXXList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXList)(nil), (*XXXList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXList_To_v1beta1_XXXList(a.(*XXXList), b.(*XXXList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXSpec)(nil), (*XXXSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(a.(*XXXSpec), b.(*XXXSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXSpec)(nil), (*XXXSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(a.(*XXXSpec), b.(*XXXSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXStatus)(nil), (*XXXStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(a.(*XXXStatus), b.(*XXXStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XXXStatus)(nil), (*XXXStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(a.(*XXXStatus), b.(*XXXStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_XXX_To_v1beta1_XXX(in *XXX, out *XXX, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1beta1_XXX_To_v1beta1_XXX is an autogenerated conversion function.
func Convert_v1beta1_XXX_To_v1beta1_XXX(in *XXX, out *XXX, s conversion.Scope) error {
	return autoConvert_v1beta1_XXX_To_v1beta1_XXX(in, out, s)
}

func autoConvert_v1beta1_XXX_To_v1beta1_XXX(in *XXX, out *XXX, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1beta1_XXX_To_v1beta1_XXX is an autogenerated conversion function.
func Convert_v1beta1_XXX_To_v1beta1_XXX(in *XXX, out *XXX, s conversion.Scope) error {
	return autoConvert_v1beta1_XXX_To_v1beta1_XXX(in, out, s)
}

func autoConvert_v1beta1_XXXList_To_v1beta1_XXXList(in *XXXList, out *XXXList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]XXX)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_XXXList_To_v1beta1_XXXList is an autogenerated conversion function.
func Convert_v1beta1_XXXList_To_v1beta1_XXXList(in *XXXList, out *XXXList, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXList_To_v1beta1_XXXList(in, out, s)
}

func autoConvert_v1beta1_XXXList_To_v1beta1_XXXList(in *XXXList, out *XXXList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]XXX)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_XXXList_To_v1beta1_XXXList is an autogenerated conversion function.
func Convert_v1beta1_XXXList_To_v1beta1_XXXList(in *XXXList, out *XXXList, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXList_To_v1beta1_XXXList(in, out, s)
}

func autoConvert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(in *XXXSpec, out *XXXSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	return nil
}

// Convert_v1beta1_XXXSpec_To_v1beta1_XXXSpec is an autogenerated conversion function.
func Convert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(in *XXXSpec, out *XXXSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(in, out, s)
}

func autoConvert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(in *XXXSpec, out *XXXSpec, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	return nil
}

// Convert_v1beta1_XXXSpec_To_v1beta1_XXXSpec is an autogenerated conversion function.
func Convert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(in *XXXSpec, out *XXXSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXSpec_To_v1beta1_XXXSpec(in, out, s)
}

func autoConvert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(in *XXXStatus, out *XXXStatus, s conversion.Scope) error {
	out.Phase = XXXPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_XXXStatus_To_v1beta1_XXXStatus is an autogenerated conversion function.
func Convert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(in *XXXStatus, out *XXXStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(in, out, s)
}

func autoConvert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(in *XXXStatus, out *XXXStatus, s conversion.Scope) error {
	out.Phase = XXXPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]v1.Condition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_XXXStatus_To_v1beta1_XXXStatus is an autogenerated conversion function.
func Convert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(in *XXXStatus, out *XXXStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_XXXStatus_To_v1beta1_XXXStatus(in, out, s)
}
